steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - hello-function
      - --gen2
      - --runtime=nodejs20
      - --region=us-central1
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=hello
      - --source=./functions/hello
options:
  logging: CLOUD_LOGGING_ONLY
